project:
  type: book # website
  output-dir: "_build"
  preview:
    port: 6789
    browser: true

# https://quarto.org/docs/books/
# https://quarto.org/docs/reference/projects/books.html
book:
  title: "Open Science and Scholarly Publishing"
  author: "Michael Rossetti"
  date: "last-modified" # "7/24/2024"
  date-format: "iso"
  #doi: "...."
  #isbn: "..."
  #issn: "..."
  #edition: "v2"

#website:

  site-url: https://s2t2.github.io/open-science-workshop-2024
  repo-url: https://github.com/s2t2/open-science-workshop-2024
  repo-branch: main
  repo-subdir: docs
  repo-actions: [edit, issue, source]
  #downloads: [pdf, epub, docx]

  # https://quarto.org/docs/websites/website-tools.html#google-analytics
  #google-analytics: "G-..."

  #sharing: [twitter, facebook]
  # https://quarto.org/docs/websites/website-tools.html#open-graph
  open-graph: true

  # https://quarto.org/docs/reference/projects/books.html#search
  search: true
    #location: sidebar # navbar, sidebar
    #type: textbox # overlay, textbox

  #cover-image: images/cover.png
  #favicon: images/favicon.ico

  # https://quarto.org/docs/websites/website-navigation.html#side-navigation
  #sidebar:
  #  logo: images/ospo-logo.png

  chapters:
    - index.md
    - quarto.md


  # shows up at bottom of page
  #body-footer: "&copy; Copyright 2024, Your Name Here"

  #page-footer:
  #  center: |
  #    <p>&copy; Copyright 2024, GWU Open Source Program Office (OSPO)</p>


#bibliography: references.bib

format:
  html:
    # https://quarto.org/docs/output-formats/html-themes.html
    theme:
      light: default #flatly
      dark: darkly
    css: styles.css
    number-sections: false
    from: markdown+emoji # enable emojis


  #pdf:
  #  documentclass: scrreprt
